project:
  type: website
  output-dir: docs
website:
  title: "Statistical Wisdom"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Articles
        href: articles.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    toc: true

editor: visual

