project:
  type: website
  output-dir: docs
website:
  title: "Statistical Wisdom"
  navbar:
    left:
      - href: index.qmd
        text: Articles
        menu:
          - text: Simple Random Sampling Is Not Simple 
          - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

